name: A Basic Workflow
on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build-app:
    runs-on: self-hosted
    steps: 
    - uses: actions/checkout@v3
    - name: Run a one line script
      run: echo "hello be!"
    - name: Run a multiline line script
      run:
        echo "hello be2!"
        echo "hello be3!"
  
  build-api:
    runs-on:  windows-latest
    steps:
      - run:  echo "Building API"

  build-db:
    needs:  build-app
    runs-on:  windows-latest
    steps:
      - run:  echo "Hello Windows"
  package:
    needs:  [build-app, build-db]
    runs-on:  self-hosted
    steps:
      - run:  echo "Hello Node6"
